name: TradeCenter
version: '1.1.0'
main: me.spaff.tradecenter.Main
api-version: '1.21'
authors: [ spaff ]
commands:
  tradecenter:
    description: All commands for TradeCenter
    permission: tc.command.execute
    aliases: [ tc ]